### PR TITLE
`WorkflowRun.doTerm` and `doKill` need to redirect back to the build

### PR DESCRIPTION
**Pull request by jglick**
Otherwise clicking the sidepanel entries for `term` / `kill` sends you to a blank page.

### CODE REVIEW

**Review by car-roll — APPROVED** [review]

**Comment by jglick** [comment]
https://github.com/jenkins-infra/helpdesk/issues/3189

**Comment by jtnord** [comment]
https://github.com/jenkinsci/bom/pull/1500#issuecomment-1291935787

**Comment by jglick** [comment]
Yeah I did not get around to updating them yet. Guess I can file PRs for that.

**Comment by jtnord** [comment]
either needs corresponding fixes in 
pipeline-graph-analysis, workflow-api, workflow-cps, workflow-durable-task-step and workflow-support or should be reverted and redone without breaking API compatability (possily using `Stapler.getCurrentResponse().forwardToPreviousPage(StaplerRequest.getCurrentRequest())` with `null` protection.

**Pull request merged**
