### PR TITLE
[JENKINS-38669] (3/3) Call `FlowDefinition.getSCMs`

### PR DESCRIPTION
**Pull request by AngryGami**
Please see https://issues.jenkins-ci.org/browse/JENKINS-38669 for explanation

Upstream PRs:
* https://github.com/jenkinsci/workflow-api-plugin/pull/111
* https://github.com/jenkinsci/workflow-cps-plugin/pull/341

### CODE REVIEW

**Comment by AngryGami** [comment]
Hm... I don't understand why it fails. I didn't change any dependencies in this project or in other PRs that I've made. It fails while enforcing version upper bound for workflow-step-api and script-security both of which are transient and I haven't touched. How to fix that?

**Comment by dwnusbaum** [comment]
@AngryGami Your dependency updates include other releases besides just your changes, and one of those releases must have updated the version of workflow-step-api or script-security that the dependency requires. To fix it, just update those plugins in this PR to the most recent version mentioned in the upper bound errors.

**Comment by AngryGami** [comment]
I'll try

**Comment by williancolognesitrimble** [comment]
any update on it? same problem here.

**Comment by jglick** [comment]
Sorry this slipped through the cracks for so long! Working on getting this released.

**Pull request merged**
