### PR TITLE
[JENKINS-62025] Pipeline console uses JS methods not supported by IE 11

### PR DESCRIPTION
**Pull request by olamy**
See [JENKINS-62025](https://issues.jenkins.io/browse/JENKINS-62025).

Signed-off-by: olivier lamy <olamy@apache.org>

### CODE REVIEW

**Comment by olamy** [comment]
@dwnusbaum I have changed this one as well. The rest looks good I was able to test  using a vbox.

**Comment by dwnusbaum** [comment]
@olamy Are you able to edit https://issues.jenkins.io/browse/JENKINS-62025? I can't change the description or mark it as "fixed but not released". I can edit other issues though, so I'm not sure what is happening.

**Comment by olamy** [comment]
@dwnusbaum done

**Comment by timja** [comment]
> @olamy Are you able to edit [issues.jenkins.io/browse/JENKINS-62025](https://issues.jenkins.io/browse/JENKINS-62025)? I can't change the description or mark it as "fixed but not released". I can edit other issues though, so I'm not sure what is happening.

@dwnusbaum issues.jenkins.io doesn't work for updates, you need to use issues.jenkins-ci.org, i'll ask in infra if we can kill the broken domain

**Comment by dwnusbaum** [comment]
@timja Ah, thanks, I didn't even realize that the link was for a different domain than normal!

**Pull request merged**
