### PR TITLE
Update Jenkins Test Harness version

### PR DESCRIPTION
**Pull request by janfaracik**
Small PR to update test harness, this is necessary as it'll unblock https://github.com/jenkinsci/jenkins/pull/6485 as some tests are failing due to an old version of `htmlunit`.

---

- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by timja — CHANGES_REQUESTED** [review]
Let's go with https://github.com/jenkinsci/workflow-job-plugin/pull/273 instead.

dependabot can't update this property

**Comment by janfaracik** [comment]
> Let's go with #273 instead.
> 
> dependabot can't update this property

Awesome - thanks! Just [slack-plugin](http://github.com/jenkinsci/slack-plugin) and [matrix-project-plugin](http://github.com/jenkinsci/matrix-project-plugin) to go, is it possible to force a `dependabot` refresh on those repos or is it easier to open PRs by hand?

**Comment by timja** [comment]
I clicked recheck for both

**Comment by timja** [comment]
did you mean matrix-auth? https://github.com/jenkinsci/bom/pull/1133/checks?check_run_id=7048329074

FYI https://github.com/jenkinsci/matrix-auth-plugin/pull/123

**Comment by janfaracik** [comment]
> did you mean matrix-auth? https://github.com/jenkinsci/bom/pull/1133/checks?check_run_id=7048329074
> 
> FYI [jenkinsci/matrix-auth-plugin#123](https://github.com/jenkinsci/matrix-auth-plugin/pull/123)

Ah yeah you're right! Cheers :)

**Pull request closed without merging**
