### PR TITLE
Allow pipeline output decoration

### PR DESCRIPTION
**Pull request by lucamilanesio**
Allow other plugins to provide a decorator to filter
the output of a Jenkins Pipeline.

### CODE REVIEW

**Comment by svanoort** [comment]
Seems reasonable to me @lucamilanesio but do you have an implementation taking advantage of the new API to go along with it?  Generally we like to have at least one consumer for net-new APIs.

**Comment by lucamilanesio** [comment]
Yes, will push shorty a plug that extends the current logstash plugin for streaming the pipeline output, will showcase as well on Tuesday at JenkinsWorld

**Comment by svanoort** [comment]
Okay, this is probably something that will be of special interest to @jglick since he's done work specifically related to external logging.

**Comment by lucamilanesio** [comment]
@jglick any feedback? The logger decoration is very useful with the current master and with the additional refactoring that you are currently doing on your PR.

**Comment by jglick** [comment]
Anyway should be obsoleted by #105.

**Comment by bitwiseman** [comment]
@lucamilanesio  Would you agree this obsolete?  Should this PR be closed?

**Pull request closed without merging**
