### PR TITLE
[JENKINS-46934] Avoid blocking forever due to log rotation

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-46934](https://issues.jenkins-ci.org/browse/JENKINS-46934)

* Call `logRotate` asynchronously.
* Impose a timeout on `Owner.get`.
* While waiting for `Owner.get`, record the build in the thread name.

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
There is timeout on log rotation here. Perhaps you misread the patch.

**Comment by abayer** [comment]
@jglick Durr. Mornings, man.

**Comment by jglick** [comment]
At any rate I suppose this is @reviewbybees done unless you change your mind.

**Comment by abayer** [comment]
Yup, was waiting to see if anyone else had any input. But they don't, so merging!

**Pull request merged**
