### PR TITLE
Deduplicate project page entries

### PR DESCRIPTION
**Pull request by NotMyFault**
Adapting the forthcoming change from https://github.com/jenkinsci/jenkins/pull/6918 to deduplicate items from the project page and the sidepanel.
The change proposed removes the "Recent changes" object, because it's already covered by the sidepanel.

### CODE REVIEW

**Comment by NotMyFault** [comment]
cc @jglick

**Comment by NotMyFault** [comment]
All checks are passing, but auto merge is blocked by a missing review 👀

**Comment by NotMyFault** [comment]
@jenkinsci/workflow-job-plugin-developers Do you mind reviewing this PR? The called forthcoming change is shipped in weeklys for a few weeks now.

**Comment by jglick** [comment]
> [@jglick](/jglick) [jglick](/jglick) merged commit [`71bba12`](/jenkinsci/workflow-job-plugin/commit/71bba124a725b0c7b2d8a1fc3aab384c26722101) into jenkinsci:master [11 hours ago](https://github.com/jenkinsci/workflow-job-plugin/pull/280#event-7443986011)

I was a little startled to see that until I realized

> [@jglick](/jglick) [jglick](/jglick) enabled auto-merge [ 2 months ago ](#event-7058746310)

and it just got approved, thus satisfying the merge condition. :grin:

**Pull request merged**
