### PR TITLE
Use SVG icons where possible

### PR DESCRIPTION
**Pull request by zbynek**
Based on jenkinsci/jenkins#5663 this makes sure icons in the sidebar and sumary use SVGs when available (core >=2.308), older versions should still use PNGs.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [n/a] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [n/a] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by NotMyFault — COMMENTED** [review]
Looks great in my tests, but don't we need to change gear to gear2 for `#getIconFileName` in `FlowGraphTableAction` as well? Afaik core (used to) ship gear2 overrides only.
Edit: It appears that has been corrected in a later release.

**Comment by NotMyFault** [comment]
@car-roll if you are the right one to review these kind of PRs 👀 


(Tagging https://github.com/jenkinsci/jenkins/pull/5778 for "on hold" reference.)

**Review by olamy — APPROVED** [review]

**Review by car-roll — APPROVED** [review]

**Comment by NotMyFault** [comment]
@car-roll Can we maybe get a release of this plugin as well?
Thanks in advance!

**Comment by jglick** [comment]
It is in https://github.com/jenkinsci/workflow-job-plugin/releases/tag/1145.v7f2433caa07f.

**Pull request merged**
