### PR TITLE
Switch to SVG icon

### PR DESCRIPTION
**Pull request by NotMyFault**
A simple change that integrates well into Jenkins modern UI based on my quick testing.
cc @jglick If you don't mind taking a look :)

<details>
<summary>Current implementation</summary>

</details>

<details>
<summary>Proposed change</summary>

</details>

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [X] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by jglick** [comment]
So this is a different icon—for a reason?

 vs.

**Comment by NotMyFault** [comment]
> So this is a different icon—for a reason?
> 
>  vs. 

I couldn't find the source the original icon is from and I didn't want to redraw it, hence I took the closest looking one I could find, released under CC0, to use that one here.

**Comment by jglick** [comment]
It just does not seem to match the style of other icons, which use shading and a 3D appearance. Current look (freestyle as of core 2.319.1, others from currently released plugins):

newJob

**Comment by NotMyFault** [comment]
I edited the showcase in the PR body to display the new proposed change. I hope it fits better :)

**Comment by jglick** [comment]
So now

 vs. 

Seems good. No strong opinion from me but I have a terrible eye. Anyone else care to review?

Originally from https://github.com/jenkinsci/pipeline-plugin/pull/375, in turn apparently from https://github.com/jenkinsci/jenkins/commit/c1a06493e4fd01b4a53a43bcf43e3c417f5f2c51. Unfortunately that did not include a record from @recena or @gusreiber of where that PNG came from so I suppose the source is lost.

**Review by jglick — APPROVED** [review]

**Pull request merged**
