### PR TITLE
Update plugin parent POM and BOM

### PR DESCRIPTION
**Pull request by basil**

### CODE REVIEW

**Comment by basil** [comment]
The changes to local data are because the local data contained unloadable builds which, though unessential to the test, caused the Windows test runs to fail when trying to clean up the Jenkins home directory because of the unloaded builds holding files open. This PR removes the unloadable builds while keeping the job definitions, which is all that the tests needed anyway.

@jenkinsci/workflow-job-plugin-developers A release of this would facilitate Java 17 PCT testing.

**Review by jglick — APPROVED** [review]
Tests from #8 & #9. I had to open the ZIPs to see the diff. For `@LocalData` it is typically recommended to unpack the ZIP (thus, e.g., `src/test/resources/org/jenkinsci/plugins/workflow/job/properties/DisableConcurrentBuildsJobPropertyTest/concurrentBuildsMigrationFromFalse/jobs/p/config.xml`) for easier tracking.

**Comment by basil** [comment]
@car-roll Would you be able to help merge and release this?

**Comment by basil** [comment]
Thank you!

**Pull request merged**
