### PR TITLE
[JENKINS-29537] Take advantage of Run.getEnvironment calling ParametersAction.buildEnvironment

### PR DESCRIPTION
**Pull request by jglick**
Downstream of https://github.com/jenkinsci/jenkins/pull/2993.

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
https://repo.azure.jenkins.io/public/ service outage?

**Comment by jglick** [comment]
@reviewbybees done

**Comment by jglick** [comment]
@abayer assuming CI passes, can this just be merged, since we are already basically using newer baselines in `master` for this plugin anyway, and if we want to backport something we could just make a 2.73.x branch?

**Comment by abayer** [comment]
@jglick Once you resolve the merge conflict, yup.

**Comment by jglick** [comment]
Is there something holding this up?

**Pull request merged**
